### ISSUE TITLE
Multi-modal training

### ISSUE THREAD

**Issue by o0t1ng0o** [Xiaoming-Yu/SingleGAN#5]
Hi, @Xiaoming-Yu .
I really appreaciate your work.
But i found some problems duraing the multi-modal training.

When i run  sh ./scripts/train_multimodal.sh  edges2handbags ,
i met the following error.

Traceback (most recent call last):
  File "./train.py", line 57, in <module>
    main()
  File "./train.py", line 16, in main
    model.initialize(opt)
  File "/data2/valentina/SingleGAN-master/models/single_gan.py", line 23, in initialize
    self.build_models()
  File "/data2/valentina/SingleGAN-master/models/single_gan.py", line 32, in build_models
    self.E = Encoder(input_nc=self.opt.input_nc, output_nc=self.opt.c_num, nef=self.opt.nef, nd=self.opt.d_num, n_blocks=4, norm_typ
  File "/data2/valentina/SingleGAN-master/models/model.py", line 245, in __init__
    conv_layers += [BasicBlock(input_ndf, output_ndf, c_norm_layer, nl_layer)]
  File "/data2/valentina/SingleGAN-master/models/model.py", line 225, in __init__
    self.shortcut = meanpoolConv(inplanes, outplanes)
  File "/data2/valentina/SingleGAN-master/models/model.py", line 207, in meanpoolConv
    sequence += [spectral_norm(Conv2dBlock(inplanes, outplanes, kernel_size=1, stride=1, padding=0, bias=True))]
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/utils/spectral_norm.py", line 128, in spectral_norm
    SpectralNorm.apply(module, name, n_power_iterations, dim, eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/utils/spectral_norm.py", line 61, in apply
    weight = module._parameters[name]
KeyError: 'weight'

Could you please fix this problem?
Many thanks!

**Comment by Xiaoming-Yu** [comment]
Hi,
I have fixed this bug in the latest version.

**Comment by o0t1ng0o** [comment]
But the version i downloaded is the latest, i still met this problem..

**Comment by Xiaoming-Yu** [comment]
Please ensure your version is the latest (updated 2018.11.21), and check your [dependencies](https://github.com/Xiaoming-Yu/SingleGAN/blob/master/requirements.txt).

**Comment by o0t1ng0o** [comment]
I fork the latest version and it fixes the problem.
Thanks!
